name: Build and Deploy to Heroku

on:
  workflow_dispatch:

  deploy-staging:
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      # possibly setup node action here...
      # possibly cache of node modules action here...
      # build steps here...
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: ${{secrets.HEROKU_EMAIL}}
          app_name: <APP_NAME_STAGING>
          branch: "develop"
          subfolder: "dist-staging"

  deploy-prod:
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      # possibly setup node action here...
      # possibly cache of node modules action here...
      # build steps here...
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: ${{secrets.HEROKU_EMAIL}}
          app_name: <APP_NAME_PROD>
          branch: "master"
          subfolder: "dist-prod"
