# This is a basic workflow to help you get started with Actions

name: Deploy to Staging

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  DeployStaging:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    needs: test-unit
    if: github.ref == 'refs/heads/develop'
    steps:
      - uses: actions/checkout@v2
      # possibly setup node action here...
      # possibly cache of node modules action here...
      # build steps here...
      - uses: onekiloparsec/heroku-node-deploy-subfolder@v1.0.4
        with:
          api_key: ${{secrets.HEROKU_API_KEY}}
          email: ${{secrets.HEROKU_EMAIL}}
          app_name: <APP_NAME_STAGING>
          branch: "develop"
          subfolder: "dist-staging"
